name: TGreen
favicon: null
layout_spectrum: 0.6129373535513878
typography_spectrum: 0.74529
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f9fd'
    - '#252a2e'
    - '#798078'
    - '#c5c4c9'
    - '#ac9fa5'
  brandStrength: 0.35946582187898457
  lightness: 0.9707535775378346
  saturation: 0.7015833300538361
  rhythmicContrast: 0.5489904067944735
purpose: []
